export const GET_ALL_CITIES = "GET_ALL_CITIES";
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const UPDATE_CITIES = "UPDATE_CITIES";
export const UPDATE_COUNTRIES = "UPDATE_COUNTRIES";
export const TOGGLE_LOADING = "TOGGLE_LOADING";